services:
  web:
    build:
      context: .
      dockerfile: Dockerfile

    image: devops-web-app:local

    container_name: devops-web-app

    ports:
      - "8080:80"

    restart: unless-stopped