name: Docker CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DOCKER_IMAGE_NAME: devops-web-app
  DOCKER_IMAGE_TAG: test

jobs:

  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t devops-web-app:test .

  test:
    name: Test Application
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Docker image
        uses: actions/download-artifact@v4
        with:
          name: docker-image

      - name: Load Docker image
        run: docker load -i docker-image.tar

      - name: Save Docker image
        run: docker save ${{ env.IMAGE_NAME }}:test -o docker-image.tar

      - name: Upload Docker image
        uses: actions/upload-artifact@v4
        with:
         name: docker-image
         path: docker-image.tar

      - name: Run container
        run: docker run -d --name test-container -p 8080:80 devops-web-app:test

      - name: Test application
        run: curl --fail http://localhost:8080

      - name: Stop container
        run: docker stop test-container