name: Conditions Practice

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  check:
    name: Check Event
    runs-on: ubuntu-latest

    steps:
      - name: Show event
        run: |
          echo "Event: ${{ github.event_name }}"

      - name: Run only on push
        if: github.event_name == 'push'
        run: |
          echo "This step runs because this workflow was triggered by a PUSH."

      - name: Run only on pull request
        if: github.event_name == 'pull_request'
        run: |
          echo "This step runs because this workflow was triggered by a PULL REQUEST."