name: Docker Build Practice

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t devops-web-app:ci .

      - name: Verify Docker image
        run: |
          docker images
          docker image inspect devops-web-app:ci